# 🔎 OpenSearch Cluster Configuration for Learning Environment
# Optimized settings for HA learning environment with 3-node cluster
# Uses consistent HA endpoints and production-ready configurations

cluster.name: "opensearch-learning-cluster"

# Node settings
node.name: "${NODE_NAME:opensearch-node}"
node.roles: ["cluster_manager", "data", "ingest"]

# Network settings
network.host: "0.0.0.0"
http.port: 9200
transport.port: 9300

# Discovery settings for 3-node cluster
discovery.seed_hosts: ["opensearch-node1", "opensearch-node2", "opensearch-node3"]
cluster.initial_cluster_manager_nodes: ["opensearch-node1", "opensearch-node2", "opensearch-node3"]

# Memory and performance settings
bootstrap.memory_lock: true
indices.memory.index_buffer_size: "10%"
indices.memory.min_index_buffer_size: "48mb"

# Index settings optimized for learning
index:
  number_of_shards: 3
  number_of_replicas: 1
  refresh_interval: "5s"
  max_result_window: 50000

# Search settings
search:
  max_buckets: 65536
  default_keep_alive: "5m"

# Thread pool settings for learning workloads
thread_pool:
  search:
    size: 4
    queue_size: 1000
  write:
    size: 4
    queue_size: 1000
  analyze:
    size: 1
    queue_size: 16

# Security settings (disabled for learning)
plugins.security.disabled: true
plugins.security.ssl.transport.enabled: false
plugins.security.ssl.http.enabled: false

# Performance monitoring settings
plugins.query.datasources.encryption.masterkey: "4fc8fee6a3fd7d6ca01772e5"

# Logging settings
logger:
  org.opensearch.discovery: INFO
  org.opensearch.cluster.service: INFO
  org.opensearch.gateway: INFO
  org.opensearch.http: INFO

# Path settings (handled by Docker)
path:
  data: "/usr/share/opensearch/data"
  logs: "/usr/share/opensearch/logs"

# Learning environment specific settings
action:
  auto_create_index: true
  destructive_requires_name: false

# Performance optimizations for learning
indices:
  fielddata:
    cache:
      size: "20%"
  requests:
    cache:
      size: "2%"
  queries:
    cache:
      size: "10%"

# Circuit breaker settings
indices.breaker:
  total.limit: "70%"
  fielddata.limit: "40%"
  request.limit: "40%"

# Cluster settings for learning stability
cluster:
  routing:
    allocation:
      disk:
        threshold_enabled: true
        low_watermark: "85%"
        high_watermark: "90%"
        flood_stage: "95%"
  max_shards_per_node: 1000

# Index State Management settings
plugins.index_state_management.enabled: true
plugins.index_state_management.job_interval: 5
plugins.index_state_management.coordinator.sweep_skip_period: 10

# Alerting settings
plugins.alerting.enabled: true
plugins.alerting.destination.allow_list: ["chime", "slack", "custom_webhook", "email", "test_action"]

# Performance Analyzer settings (for learning insights)
plugins.performance_analyzer.agent.stats_collector.cluster_stats_collector.enabled: true
plugins.performance_analyzer.agent.stats_collector.node_stats_collector.enabled: true

# Cross-cluster search settings
cluster.remote_cluster_client.enabled: false

# Snapshot settings for learning
cluster.routing.allocation.snapshot_relocation_enabled: true

# Learning environment compatibility
compatibility.override_main_response_version: true
